# Generated by Django 4.2.2 on 2023-06-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('education', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('portfolio', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
